version: '3.12.12'

services:
  app:
    build: .
    networks:
      - global-network
    volumes:
      - VolumeT8:/VolumeT8

networks:
  global-network:
    external: true

volumes:
  VolumeT8:
    external: true